# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        gemfile:
          - rails_6_1
          - rails_7_0
          - rails_7_1
          - rails_7_2
          - rails_8_0
          - rails_8_1
        exclude:
          - ruby-version: '3.4'
            gemfile: rails_6_1
          - ruby-version: '3.4'
            gemfile: rails_7_0
          - ruby-version: '3.4'
            gemfile: rails_7_1
          - ruby-version: '3.3'
            gemfile: rails_6_1
          - ruby-version: '3.3'
            gemfile: rails_7_0
          - ruby-version: '2.7'
            gemfile: rails_7_2
          - ruby-version: '3.0'
            gemfile: rails_7_2
          - ruby-version: '2.7'
            gemfile: rails_8_0
          - ruby-version: '3.0'
            gemfile: rails_8_0
          - ruby-version: '3.1'
            gemfile: rails_8_0
          - ruby-version: '2.7'
            gemfile: rails_8_1
          - ruby-version: '3.0'
            gemfile: rails_8_1
          - ruby-version: '3.1'
            gemfile: rails_8_1
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
